### ISSUE TITLE
Clone of SimpleClass too slow

### ISSUE THREAD

**Issue by Tornhoof** [ReubenBond/DeepCopy#6]
Hi, during benchmarking of #1 I noticed, that the SimpleClass clone is quite slow, due to the recording of the same instance logic.
I benchmarked a  few different versions:
- Your current one
- Removing the context handling in the IL code
- Removing the context handling and calling the delegate directly
- Expression Tree version for properties I'm currently using
- simply calling doing a ``new SimpleClass`` with the values (pure ctor and property assignment)

|                    Method               |     Mean |     Error |    StdDev |  Gen 0 | Allocated |
|-----------------------------------------|---------:|----------:|----------:|-------:|----------:|
|                    SimpleClass_DeepCopy | 108.1 ns | 0.1503 ns | 0.1333 ns | 0.0122 |      64 B |
|     SimpleClass_DeepCopy_WithoutContext | 41.70 ns | 0.1472 ns | 0.1305 ns | 0.0122 |      64 B |
|	  SimpleClass_Delegate_WithoutContext | 15.14 ns | 0.0216 ns | 0.0202 ns | 0.0122 |      64 B |
|              SimpleClass_ExpressionTree | 58.47 ns | 0.8300 ns | 0.7357 ns | 0.0122 |      64 B |
|                         SimpleClass_New | 7.969 ns | 0.0146 ns | 0.0136 ns | 0.0122 |      64 B |

I think it might useful to find a way how to clone an object without the context and only handle the context if it's necessary.
For example:
Only add the context handling part for arrays, lists of classes etc (primitive types and structs shouldn't need it, you already do that most of the time afaik) and provide two versions, one for lists and one for direct calls

I admit this might get ugly with nested objects, but nested objects usually are bigger so it won't impact as much, if at all, I guess having a fast path for plain and simple c# objects would nice.

**Comment by ReubenBond** [comment]
Essentially you're saying: analyze the object graph and determine if a cycle could appear, then only record instances which might appear in a cycle.

Is that right?

Currently SimpleClass would be tracked, but none of its fields would (since value types aren't tracked).

This is deep into micro-optimization territory, but it's fun. Would you like to have a look into implementing those optimizations? It would be interesting to see how far it can be taken.

In the SimpleClass_New benchmark, it would be good to set each property on the new instance.

What's your Expression Tree impl?

**Comment by Tornhoof** [comment]
Yes, checking the object graph would be my idea. I have a simple version ready in a few minutes.
Current idea:
- Short circuit for object (we can't reason for type object) -> always track
- Check all fields, if any of the field types is non-immutable or was seen before -> track

This simple version only solves the SimpleClass case (e.g. all fields are immutable). It achieves the performance of SimpleClass_DeepCopy_WithoutContext test case above.

|               Method |     Mean |     Error |    StdDev |  Gen 0 | Allocated |
|--------------------- |---------:|----------:|----------:|-------:|----------:|
| SimpleClass_DeepCopy | 38.41 ns | 0.0237 ns | 0.0210 ns | 0.0122 |      64 B |

The following cases could be handled, but I'm not certain they are worth pursuing:
- More complex objects with nested children
- Lists, arrays etc. of immutable types

As for my expression tree version, it basically only sets the properties from right side to the left side and is only designed for those primitive classes like SimpleClass.

**Comment by Tornhoof** [comment]
I thought a bit more in detail yesterday about the object graph problem, let's first define what Immutability is and then go from there.

One definition is: "Changing a value on the copied object has no impact on the original object"
Let's ignore ref for now (like in the source code)
This includes:
**1. all primitive types**
**2. all value types where all fields are from 1. or 2. (recursive)**

Currently we also include some classes like Uri and Tuple, which are defined as immutable. Do we want that?

**3. all classes where all fields are readonly and from 1,2,3. (not yet fully implemented)**

For the immutable types we don't copy, we simply assign the current value from the original object.

As you explained in the pull request comments it is necessary to pass the root type through the graph to find out if we need to track it and we need to repeat
this for each branch recursively.
The only solution I currently see is having unique copy methods for each unique object graph (we only care for the type in the graph, not the arity).
All my current ideas here basically result in e.g. IL enumerable handling for lists etc. which gets complicated fairly fast and error prone too.

I we don't assume 3. is true than I don't see any other solution than the one above.

Does the following hold true: "Any immutable object graph does not need tracking"?

Let's see, for root types of 1,2,3 it is true, so let's look at other types.

**4. If a type has two fields of the same assignable type and are not of 1,2,3, they could reference the same instance so we need to track**
**5. If a type has a field of an enumerable type (array, list etc.) we need to track as one or more instances in the enumerable could be the same and are not of 1,2,3**
**6. If a type has a field of either 4,5,6 (recursive) we need to track**

Did I miss anything?

I currently can't find any object graph which is immutable as defined by 1,2,3 which would need tracking, so the more I think about it, the whole question is simply 
about the problem of immutability.

**Comment by ReubenBond** [comment]
> One definition is: "Changing a value on the copied object has no impact on the original object"

I would define immutability for the purposes of this library as: "The object is never modified after construction". The other definition sounds more like the definition of a value type / shallow-copyable type.

> Currently we also include some classes like Uri and Tuple, which are defined as immutable. Do we want that?

As you pointed out in another issue, we need to check the properties of the generic parameters.

> Does the following hold true: "Any immutable object graph does not need tracking"?
Let's see, for root types of 1,2,3 it is true, so let's look at other types.

For root types I believe that's correct.

> I currently can't find any object graph which is immutable as defined by 1,2,3 which would need tracking, so the more I think about it, the whole question is simply
about the problem of immutability.

How about `ValueTuple<string, string>`? We need to track the `string` values, even though `ValueTuple` and `string`  and hence `ValueTuple<string, string>` are immutable.

**Comment by Tornhoof** [comment]
Maybe I don't follow, but why do you want to track ``string``?

**Comment by ReubenBond** [comment]
@Tornhoof In general, there are two reasons to track objects:
1. to prevent infinite recursion in cyclic object graphs
2. in order to maintain reference equality

I think what you're suggesting is that you can prove certain types can appear in a cycle (where the root type is known), but in that case you might need to drop support for reference equality for cases where an object won't appear in a cycle.

I'm fine with that, I think maintaining reference equality is not a strong use-case in general. So, relaxing that requirement, I think your logic is sound.

**Comment by Tornhoof** [comment]
I think your your example is Point 5 in my listing:
>> If a type has a field of an enumerable type (array, list etc.) we need to track as one or more instances in the enumerable could be the same and are not of 1,2,3

Admittingly this applies to root level arrays too.
I don't think you need to relax that requirement at all, it should be covered by 1-6. As I said, I can't think of any example where this does not hold true.

**Comment by ReubenBond** [comment]
I mean relaxing the requirement for reference equality, since `ValueTuple<string, string>` (or `ValueTuple<MyImmutableType, MyImmutableType>` would be 'immutable' by this definition and would not have references tracked and therefore copying `ValueTuple.Create(immutable, immutable)` would yield a result where `object.ReferenceEquals(copy.Item1, copy.Item2)` is `false`.

**Comment by Tornhoof** [comment]
Why?
If Item1-N are immutable in the ValueTuple we assign the same values references in the clone, so after the clone Item1-N share the same equality properties as the original.
```csharp
string input = "Hello World";
var vt1 = ValueTuple.Create(input, input);
var eq = ReferenceEquals(vt1.Item1, vt1.Item2);
Debug.Assert(eq);

var vt2 = ValueTuple.Create(vt1.Item1, vt1.Item2);
var eq2 = ReferenceEquals(vt2.Item1, vt2.Item2);
Debug.Assert(eq2);
````

**Comment by ReubenBond** [comment]
I thought the idea was to disable reference tracking for types which fit the criteria above

**Comment by Tornhoof** [comment]
You mean Rule 4?
>> 4. If a type has two fields of the same assignable type and are not of 1,2,3, they could reference the same instance so we need to track

``string`` and ``MyImmutableType`` are covered by 1,2,3 so no need to track. That's what my code example does.
You can extend rule 4 with two or more fields:
4. If a type has two or more fields of the same assignable type which are not of 1,2,3, they could reference the same instance, so we need to track

**Comment by ReubenBond** [comment]
My bad. Your rules seem correct to me

**Comment by Tornhoof** [comment]
We can close this, the branch is merged.
