### ISSUE TITLE
ImmutabilityCheck for generic types is wrong

### ISSUE THREAD

**Issue by Tornhoof** [ReubenBond/DeepCopy#9]
There is a bug in the immutability check, I had the pull request for. Currently we only check if the genericTypeDef is immutable, but we need to check each TypeArg of the constructed type too.
Currently:
``KeyValuePair<string,string>`` -> Immutable
``KeyValuePair<string,Poco>``  -> Immutable
Expected:
``KeyValuePair<string,Poco>``  -> Mutable

Repro:
```csharp
[Fact]
public void CanCopyMutableKeyValuePair()
{
    var original = new KeyValuePair<string, Poco>("Hello", new Poco());
    var result = DeepCopier.Copy(original);
    Assert.Same(original.Key, result.Key);
    Assert.NotSame(original.Value, result.Value);
}
```

I tried to fix that by changing the check to:
```csharp
 if (type.IsGenericType && this.policies.TryGetValue(type.GetGenericTypeDefinition(), out result))
 {
     if (result == Policy.Immutable)
     {
         var generigArgs = type.GetGenericArguments();
         result = generigArgs.All(IsImmutable) ? Policy.Immutable : Policy.Mutable;
     }
     return this.policies[type] = result;
 }
```
but then I get ExecutionEngine Exceptions after running tests and not necessarily in the same order.

**Comment by ReubenBond** [comment]
Good point. Immutability needs to take into account mutability of type arguments unless the containing type is the special `Immutable<T>` type.

Do you know why those exceptions are occurring?

**Comment by Tornhoof** [comment]
No, I have no idea:
Reason for test abort is empty:
``[07.11.2017 13:19:37 Error] Der aktive Testlauf wurde abgebrochen. Grund: `` (which basically means Testrun was aborted. Reason)
The EngineException itself is empty.
The only thing I can find is, that if I run the tests in Visual Studio, the following three test runs are not executed anymore:
CanCopyArray,CanCopyIntegers,CanCopyString
I tried resetting the CopyPolicy after each test run, didn't help.

Best idea I have is actually some kind of corruption in the runtime after running the tests.

**Comment by Tornhoof** [comment]
I think I have a fix ready and I think those execution engine are gone after restarting VS, I don't know how far the test engine is reused and it might be some corruption during internal testing

**Comment by Tornhoof** [comment]
This was fixed in https://github.com/ReubenBond/DeepCopy/pull/10. Let's close this.
